org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.org.testcontainers=warn
org.slf4j.simpleLogger.log.tc=error
org.slf4j.simpleLogger.log.com.github.dockerjava=error
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.logFile=System.err
org.slf4j.simpleLogger.log.org.testcontainers.utility.ResourceReaper=error
